config/routes.rb
Rails.application.routes.draw do

  resources :answers
  resources :questions

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord

  belongs_to :question

  def gravatar
    "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(email)}"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord

  has_many :answers

  def gravatar
    "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(email)}"
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def show
    # @answer = Answer.find_by_question_id(params[:id])
  end

  def create
    question = Question.find(params[:answer][:question_id])
    question.answers.create(answer_params)
    redirect_to question
  end

  private

  def answer_params
    params.require(:answer).permit(:question_id, :email,:body)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @questions = Question.order(created_at: :desc).all
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def show
    @question = Question.find(params[:id])
  end

  def create
    Question.create(question_params)

    redirect_to root_path
  end

  private

  def question_params
    params.require(:question).permit(:email,:body)
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href='/' class="navbar-brand">History of the Universe</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <form><a href="#" class="btn btn-success navbar-btn btn-sm" data-toggle="modal" data-target="#new-question-modal">Ask Question</a></form>
        </li>
      </ul>
    </div>

  </div>
</nav>

app/views/home/_new_answer_form.html.erb
<div class="modal fade" id="new-answer-modal" tabindex="-1">

  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span>&times;</span>
        </button>
        <h4>New Answer</h4>
      </div>

      <div class="modal-body">

        <%= form_for :answer, url: '/answers', html: { class: 'form-horizontal'} do %>

            <input type="hidden" name="answer[question_id]" value="<%= @question.id %>">
            <div class="form-group">
              <label for="inputEmail" class="col-sm-2 control-label">Email</label>
              <div class="col-sm-10">
                <input type="email" name="answer[email]" class="form-control" id="inputEmail" placeholder="Email" required>
              </div>
            </div>

            <div class="form-group">
              <label for="inputQuestion" class="col-sm-2 control-label">Answer</label>
              <div class="col-sm-10">
                <textarea id="inputQuestion" name="answer[body]" class="form-control" placeholder="What's your answer?" required></textarea>
              </div>
            </div>


            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>

        <% end %>


      </div>


    </div>
  </div>

</div>

app/views/home/_new_question_form.html.erb
<div class="modal fade" id="new-question-modal" tabindex="-1">

  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span>&times;</span>
        </button>
        <h4>New Question</h4>
      </div>

      <div class="modal-body">

        <%= form_for :question, url: '/questions', html: { class: 'form-horizontal'} do %>

          <div class="form-group">
            <label for="inputEmail" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
              <input type="email" name="question[email]" class="form-control" id="inputEmail" placeholder="Email" required>
            </div>
          </div>

          <div class="form-group">
            <label for="inputQuestion" class="col-sm-2 control-label">Question</label>
            <div class="col-sm-10">
              <textarea id="inputQuestion" name="question[body]" class="form-control" placeholder="What would you like to know?" required></textarea>
            </div>
          </div>


          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary" >Submit</button>
          </div>

        <% end %>


      </div>


    </div>
  </div>

</div>

app/views/home/index.html.erb
<div class="well">
  <h3>Main tagline about the organization</h3>
  <h4>Secondary tagline about the organization</h4>
</div>

<% @questions.each do |q| %>
  <div class="media">
    <div class="media-left">
      <a href="#">
        <%#= image_tag('dummyProfileMediaObj.svg', :class => "media-object") %>
        <%#= image_tag('http://www.gravatar.com/avatar/424242', :class => "media-object") %>
        <%= image_tag(q.gravatar) %>
      </a>
    </div>

    <div class="media-body">
      <h4 class="media-heading"><%= q.email %> asked:</h4>
      <div><%= q.body %></div>
      <div><sm><%= time_ago_in_words q.created_at.to_datetime %> ago</sm></div>
      <div><a href="<%= question_path(q) %>" class="btn btn-success btn-xs">Answers</a></div>
    </div>
  </div>
<% end  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HU</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <div class="container-fluid">

      <%= render 'home/navbar' %>

      <%= yield %>

    </div>

    <!--modal-->
    <%= render 'home/new_question_form'	  %>


  </body>
</html>

app/views/questions/show.html.erb
<div class="media">
  <div class="lead well">

    <div class="media">
      <div class="media-left">
      <a href="#">
        <%= image_tag(@question.gravatar) %>
      </a>
      </div>

      <div class="media-body">
        <h4 class="media-heading"><%= @question.email %> asked:</h4>
        <%= @question.body %>
      </div>
    </div>

  </div>


  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      
      <div><button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#new-answer-modal">Submit new answer</button></div>
      <%= render 'home/new_answer_form' %>

      <% @question.answers.each do |a| %>
        <div class="media">
          <div class="media-left">
            <a href="#">
              <%#= image_tag('dummyProfileMediaObj.svg') %>
              <%= image_tag(a.gravatar) %>
            </a>
          </div>

          <div class="media-body">
            <h4 class="media-heading"><%= a.email %> answered:</h4>
            <%= a.body %>
          </div>
        </div>
      <% end %>

    </div>
  </div>



</div>